sudo: required
services:
    - docker

before_install:
    - docker build -t hdimessi/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true hdimessi/react-test npm run test

after_success:
    - docker build -t hdimessi/multi-client ./client
    - docker build -t hdimessi/multi-nginx ./nginx
    - docker build -t hdimessi/multi-server ./server
    - docker build -t hdimessi/multi-worker ./worker
    # Login to the docker CLI
    - echo "DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images to docker hub
    - docker push hdimessi/multi-client 
    - docker push hdimessi/multi-nginx
    - docker push hdimessi/multi-server 
    - docker push hdimessi/multi-worker 